Repository ROCm/rocPyDecode, pull requests merged in 2024-10, with the labels that each got.

#103 rocPyDecode version everywhere is 0.2.0 now, to avoid version mismatch
  CHANGELOG.md
  CMakeLists.txt
  rocPyDecode-requirements.py
  setup.py
Labels: bugfix

#105 Not using CodecSupported() API from rocDecode if ROCM version less than 6.3
  CMakeLists.txt
  src/roc_pyvideodecode.cpp
Labels: ci:precheckin

#107 Fixing CI build issues and install the wheel when building
  build_rocpydecode_wheel.py
Labels: ci:precheckin

#109 Adding check for dlpack package in cmake
  CMakeLists.txt
Labels: dependencies, ci:precheckin

#110 Adding details on how to build/install the wheel in the README.MD file
  README.md
Labels: ci:docs-only

#113 Removing pybind11Header var and its related import from setup file
  setup.py
Labels: enhancement, ci:precheckin

#111 Install rocpydecode on CI as sudo
  .jenkins/common.groovy
Labels: ci:precheckin

#116 Updating the CHANGELOG.md file for rocPyDecode
  CHANGELOG.md
Labels: documentation, enhancement, ci:docs-only

#121 added link to documentation
  README.md
Labels: documentation, ci:docs-only

#117 Samples using rocDecode package videos instead of rocPyDecode
  rocPyDecode-docker-install.py
  samples/CMakeLists.txt
Labels: enhancement
