Repository ROCm/rocPyDecode, pull requests merged in 2024-09, with the labels that each got.

#80 Adding rst API docs
  .gitignore
  docs/data/reference/rocPyDecodeArch.png
  docs/how-to/using-rocPydecode.rst
  docs/index.rst
  docs/install/install.rst
  docs/reference/decoderClass.rst
  docs/reference/demuxerClass.rst
  docs/reference/rocPyDecode.rst
  docs/reference/structures.rst
  docs/sphinx/_toc.yml.in
  docs/tutorials/README.md
Labels: documentation

#83 Reference 621
  .gitignore
  README.md
  docs/data/reference/rocPyDecodeArch.png
  docs/how-to/using-rocPydecode.rst
  docs/index.rst
  docs/install/install.rst
  docs/reference/decoderClass.rst
  docs/reference/demuxerClass.rst
  docs/reference/rocPyDecode.rst
  docs/reference/structures.rst
  docs/sphinx/_toc.yml.in
  docs/tutorials/README.md
  docs/what-is-rocPyDecode.rst
Labels: documentation, ci:docs-only

#88 External CI enablement for rocPyDecode
  .azuredevops/rocm-ci.yml
Labels: enhancement

#87 PyPacketData address update
  pyRocVideoDecode/decoder.py
  samples/videodecode.py
  samples/videodecodemem.py
  samples/videodecodeperf.py
  samples/videodecodergb.py
  samples/videodecodetorch.py
  samples/videodecodetorch_resnet50.py
  src/roc_pydecode.cpp
  src/roc_pydecode.h
  src/roc_pyvideodecode.cpp
  src/roc_pyvideodemuxer.cpp
Labels: ci:precheckin

#99 Create rocPyDecode Python distribution wheel
  CMakeLists.txt
  build_rocpydecode_wheel.py
  setup.py
  src/roc_pybuffer.cpp
Labels: ci:precheckin
