Repository ROCm/rocPyDecode, pull requests merged in 2024-08, with the labels that each got.

#70 Build option for user to choose target ASIC
  CMakeLists.txt
  README.md
  setup.py
Labels: bugfix

#68 Cherry pick documentation updates (#62) to 6.2 release branch
  README.md
  docs/.gitignore
  docs/how-to/using-rocPydecode.rst
  docs/index.rst
  docs/install/install.rst
  docs/license.md
  docs/license.rst
  docs/sphinx/.gitignore
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  docs/tutorials/README.md
  docs/what-is-rocPyDecode.rst
Labels: documentation, bugfix

#73 Build cpp files in parallel
  CMakeLists.txt
  README.md
  setup.py
Labels: enhancement, bugfix

#78 Adding GetCaps to check if codec is supported, generating msg otherwise
  pyRocVideoDecode/decoder.py
  pyRocVideoDecode/demuxer.py
  samples/videodecode.py
  samples/videodecodemem.py
  samples/videodecodeperf.py
  samples/videodecodergb.py
  samples/videodecodetorch.py
  samples/videodecodetorch_resnet50.py
  src/roc_pyvideodecode.cpp
  src/roc_pyvideodecode.h
  src/roc_pyvideodemuxer.cpp
  src/roc_pyvideodemuxer.h
Labels: enhancement
