Repository ROCm/rocPyDecode, pull requests merged in 2024-11, with the labels that each got.

#125 updated the changelog for 6.3
  CHANGELOG.md
Labels: documentation, ci:docs-only

#126 GPU Arch - Updates
  CMakeLists.txt
  docs/install/install.rst
Labels: enhancement, bugfix, ci:precheckin

#122 Depending on installing pybind11 using pip3 instead of apt
  CMakeLists.txt
  README.md
  cmake/Findpybind11.cmake
  rocPyDecode-requirements.py
  samples/CMakeLists.txt
Labels: enhancement, ci:precheckin

#124 Adding conda package build scripts and README
  README.md
  conda-recipe/README.md
  conda-recipe/meta.yaml
Labels: documentation, enhancement, ci:precheckin

#127 ROCm 6.3.0 - Cherry-pick: GPU Arch - Updates (#126)
  CMakeLists.txt
Labels: enhancement
