Repository ROCm/rocPyDecode, pull requests merged in 2025-05, with the labels that each got.

#184 Bug_fix: ffmpeg_call_adding_ctest_to_boost_code_coverage
  pyRocVideoDecode/decodercpu.py
  samples/rocjpeg/batch_sample.ipynb
  samples/rocjpeg/decode_rgb_planar.ipynb
  samples/rocjpeg/decode_source.ipynb
  src/rocdecode/roc_pyvideodecodecpu.cpp
  src/rocdecode/roc_pyvideodecodecpu.h
  tests/CMakeLists.txt
  tests/decoder_test.py
  tests/decodercpu_test.py
  tests/demuxer_test.py
Labels: bugfix, ci:precheckin

#187 Adding_API_Test_Calls_For_Code_Coverage
  samples/rocjpeg/batch_sample.ipynb
  samples/rocjpeg/decode_rgb_planar.ipynb
  tests/decoder_test.py
Labels: enhancement, ci:precheckin

#189 Disable_Tests_When_Torch_not_Present
  tests/CMakeLists.txt
Labels: bugfix, ci:precheckin

#190 Bug_Fix_2_Samples
  samples/rocdecode/videodecode_cpu_backend.py
  samples/rocdecode/videodecodetorch_resnet50.py
Labels: bugfix, ci:precheckin

#192 fixed a broken link due to the samples moving (#185)
  docs/how-to/using-rocPydecode.rst
Labels: documentation, ci:docs-only

#191 CI - Adding_selfTest_for_CCOV_Boost
  src/rocdecode/roc_pydecode.cpp
  src/rocdecode/roc_pydecode_test.cpp
  src/rocdecode/roc_pyvideodecodecpu.cpp
  src/rocdecode/roc_pyvideodecodecpu.h
  tests/CMakeLists.txt
  tests/decoder_api_test.py
Labels: enhancement, ci:precheckin
