Repository ROCm/rocPyDecode, pull requests merged in 2025-01, with the labels that each got.

#149 Bug fix adding gfx1200 & 1201 to the supported GPU list
  CMakeLists.txt
Labels: bugfix

#145 Adding version attribute in rocPyDecode module
  src/roc_pydecode.cpp
Labels: enhancement, ci:precheckin

#131 Adding videodecode Jupyter's notebook sample
  samples/README.md
  samples/jupyter_notebooks/videodecode.ipynb
Labels: enhancement, ci:precheckin

#140 Using MD5 functionality from its new MD5 class
  CHANGELOG.md
  src/roc_pyvideodecode.cpp
  src/roc_pyvideodecode.h
Labels: documentation, enhancement, ci:precheckin

#141 Enabling FFMpegVideoDecoder class provider adding 2 python samples
  CMakeLists.txt
  pyRocVideoDecode/decodercpu.py
  samples/videodecode_cpu_backend.py
  samples/videodecodetorch_cpu_backend.py
  src/roc_pydecode.cpp
  src/roc_pydecode.h
  src/roc_pyvideodecodecpu.cpp
  src/roc_pyvideodecodecpu.h
Labels: documentation, enhancement, ci:precheckin

#147 Initial commit of refactored install and landing page
  docs/conf.py
  docs/index.rst
  docs/install/install.rst
  docs/install/rocPyDecode-install.rst
  docs/install/rocPyDecode-prerequisites.rst
  docs/reference/rocPyDecode-codecs-and-hardware.rst
  docs/sphinx/_toc.yml.in
Labels: documentation, ci:docs-only

#153 Removing MD5 functionality, APIs, sample code, and documentation
  CHANGELOG.md
  CMakeLists.txt
  conda-recipe/meta.yaml
  docs/reference/decoderClass.rst
  docs/reference/structures.rst
  pyRocVideoDecode/decoder.py
  pyRocVideoDecode/decodercpu.py
  rocPyDecode-requirements.py
  samples/jupyter_notebooks/videodecode.ipynb
  samples/videodecode.py
  setup.py
  src/roc_pydecode.cpp
  src/roc_pyvideodecode.cpp
  src/roc_pyvideodecode.h
  src/roc_pyvideodecodecpu.cpp
  src/roc_pyvideodecodecpu.h
Labels: enhancement, ci:precheckin

#154 Doc - Updates
  README.md
  docs/install/rocPyDecode-install.rst
  docs/install/rocPyDecode-prerequisites.rst
  samples/jupyter_notebooks/videodecode.ipynb
Labels: enhancement, ci:docs-only, bugfix
