Repository ROCm/rocPyDecode, pull requests merged in 2025-07, with the labels that each got.

#208 Adding rocPyJpegDecode to rocPyDecode Landing Page
  README.md
  docs/data/AMD_rocPyDecode_Logo.png
Labels: ci:docs-only

#211 Doc - updates for ROCm 7.0.0
  CHANGELOG.md
  README.md
Labels: documentation, enhancement, ci:docs-only

#214 rocJPEG Bindings - updates and fixes
  CMakeLists.txt
  rocPyDecode-requirements.py
  tests/CMakeLists.txt
Labels: bugfix, ci:precheckin

#218 Correcting _JPEG_PyBind_Sample_install_location
  tests/CMakeLists.txt
Labels: enhancement, bugfix, ci:precheckin

#219 Package - set rocjpeg required
  CHANGELOG.md
  CMakeLists.txt
  README.md
  cmake/FindFFmpeg.cmake
  conda-recipe/README.md
  conda-recipe/meta.yaml
  docs/install/rocPyDecode-cmake-install.rst
  rocPyDecode-requirements.py
  setup.py
  src/rocdecode/roc_pydecode.cpp
  src/rocjpeg/roc_pyjpeg.cpp
  tests/CMakeLists.txt
Labels: enhancement, bugfix, ci:precheckin

#222 Enhancement - Lib dependency fix
  CMakeLists.txt
Labels: enhancement, ci:precheckin

#213 DOCs: Adding samples Docs for rocPyJpegDecode
  README.md
  samples/README.md
  samples/rocdecode/README.md
  samples/rocjpeg/README.md
Labels: enhancement, ci:docs-only, ci:precheckin

#227 Update requirements.in
  docs/sphinx/requirements.in
Labels: documentation, ci:docs-only
