Repository ROCm/rocPyDecode, pull requests merged in 2025-03, with the labels that each got.

#166 Updated the installation section
  docs/index.rst
  docs/install/rocPyDecode-cmake-install.rst
  docs/install/rocPyDecode-install.rst
  docs/install/rocPyDecode-pip-install.rst
  docs/install/rocPyDecode-prerequisites.rst
  docs/reference/demuxerClass.rst
  docs/sphinx/_toc.yml.in
Labels: documentation, ci:docs-only

#174 Using the new macro ROCDECODE_CHECK_VERSION
  CMakeLists.txt
  src/roc_pyvideodecode.cpp
  src/roc_pyvideodecode.h
  src/roc_pyvideodecodecpu.cpp
  src/roc_pyvideodecodecpu.h
  tests/CMakeLists.txt
Labels: enhancement, ci:precheckin

#176 Bug_Fix_P1_Ticket_SWDEV-521676
  CMakeLists.txt
Labels: bugfix
